# -*- coding: utf-8 -*-
"""DUENet_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_u7ITK2XD19ILJQ3v8IfKQDsDBcPbSg
"""

## DUENet

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torch.optim import Adam
from torch.optim.lr_scheduler import CosineAnnealingLR
import time
import os

# CONFIG

CONFIG = {
    # Data
    'n_bands':          188,
    'n_classes':        12,
    'patch_size':       9,

    # Training
    'batch_size':       64,
    'epochs':           50,
    'lr':               3e-4,
    'num_workers':      2,

    # Loss weights
    'gamma1':           0.6,
    'gamma2':           0.4,
    'beta_kl':          0.1,
    'kl_warmup_epochs': 8,

    # Architecture — full scale
    'latent_dim':       64,
    'num_primary_caps': 16,
    'primary_cap_dim':  8,
    'class_cap_dim':    16,

    # DTW
    'dtw_num_prototypes': 32,
    'dtw_proto_len':      24,
    'dtw_bandwidth':       4,

    # Gaussian interpolation
    'gauss_num_kernels':  16,

    # Checkpointing
    'save_dir':         '/content/',
    'save_every':       10,         # save periodic checkpoint every N epochs
}

MINERAL_NAMES = [
    'Alunite', 'Andradite', 'Buddingtonite', 'Dumortierite',
    'Kaolinite_1', 'Kaolinite_2', 'Muscovite', 'Montmorillonite',
    'Nontronite', 'Pyrope', 'Sphene', 'Chalcedony'
]

NUM_CLASSES      = CONFIG['n_classes']
LATENT_DIM       = CONFIG['latent_dim']
NUM_PRIMARY_CAPS = CONFIG['num_primary_caps']
PRIMARY_CAP_DIM  = CONFIG['primary_cap_dim']
CLASS_CAP_DIM    = CONFIG['class_cap_dim']
N_BANDS          = CONFIG['n_bands']

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

os.makedirs(CONFIG['save_dir'], exist_ok=True)

# DATASET

DATA_DIR = '/content/'
hsi        = np.load(DATA_DIR + 'hsi.npy').astype(np.float32)
abundances = np.load(DATA_DIR + 'abundances.npy').astype(np.float32)

if hsi.shape[0] < hsi.shape[1]:
    hsi = hsi.transpose(1, 2, 0)
if abundances.shape[0] == CONFIG['n_classes']:
    abundances = abundances.transpose(1, 2, 0)

rows, cols, _ = hsi.shape
label_map     = np.argmax(abundances, axis=2)
print(f"HSI shape: {hsi.shape}  |  classes: {NUM_CLASSES}")

# print class distribution - no. of pixels in each mineral class
class_counts = np.bincount(label_map.flatten(), minlength=NUM_CLASSES)
print("\nClass distribution:")
for i, (name, count) in enumerate(zip(MINERAL_NAMES, class_counts)):
    pct = 100 * count / label_map.size
    print(f"  {i:2d} {name:<20s}: {count:6,d} ({pct:5.1f}%)")

# padding image
HALF = CONFIG['patch_size'] // 2
# reflect mode: mirrors neighboring pixels
hsi_padded = np.pad(hsi,
    pad_width=((HALF, HALF), (HALF, HALF), (0, 0)),
    mode='reflect')


class CupriteDataset(Dataset):
    def __init__(self, coords, hsi_padded, abundances, label_map, patch_size):
        self.coords     = coords
        self.hsi_padded = hsi_padded
        self.abundances = abundances
        self.label_map  = label_map
        self.half       = patch_size // 2

    def __len__(self):
        return len(self.coords)

    def __getitem__(self, idx):
        r, c  = self.coords[idx]
        r_pad    = r + self.half
        c_pad    = c + self.half
        patch = self.hsi_padded[r_pad-self.half:r_pad+self.half+1,
                                c_pad-self.half:c_pad+self.half+1, :]
        patch = patch.transpose(2, 0, 1)
        return (torch.tensor(patch, dtype=torch.float32),
                torch.tensor(abundances[r, c], dtype=torch.float32),
                torch.tensor(label_map[r, c], dtype=torch.long))


np.random.seed(20)
all_coords  = np.array([(r, c) for r in range(rows) for c in range(cols)])

shuffle = np.random.permutation(len(all_coords))
n_train = int(len(all_coords) * 0.7)
train_coords = all_coords[shuffle[:n_train]]
test_coords  = all_coords[shuffle[n_train:]]

train_loader = DataLoader(
    CupriteDataset(train_coords, hsi_padded, abundances,
                   label_map, CONFIG['patch_size']),
    batch_size=CONFIG['batch_size'], shuffle=True,
    num_workers=CONFIG['num_workers'], pin_memory=True)

test_loader = DataLoader(
    CupriteDataset(test_coords, hsi_padded, abundances,
                   label_map, CONFIG['patch_size']),
    batch_size=CONFIG['batch_size'], shuffle=False,
    num_workers=CONFIG['num_workers'], pin_memory=True)

print(f"Train: {len(train_loader)} batches | Test: {len(test_loader)} batches")


# DTW SIMILARITY LAYER

class DTWSimilarityLayer(nn.Module):
    # spectral_dim: original spectral length
    # num_prototypes: no. of prototypes
    # proto_len: compressed spectrum length
    # bandwidth: Sakoe-Chiba constraint: to compare nearby points only
    # gamma: softness parameter for SoftDTW
    def __init__(self, in_channels, spectral_dim,
                 num_prototypes, proto_len, bandwidth, gamma=1.0):
        super().__init__()
        self.proto_len = proto_len
        self.bandwidth = bandwidth
        self.gamma = gamma

        # Initialize weights using: N(0,0.01)^2 (very small weights)
        self.prototypes = nn.Parameter(torch.randn(num_prototypes, proto_len) * 0.1)
        self.spec_compress = nn.AdaptiveAvgPool1d(proto_len)
        self.log_scale = nn.Parameter(torch.tensor(0.0))

        self.proj = nn.Linear(num_prototypes, in_channels, bias=True)
        # very small random values
        nn.init.normal_(self.proj.weight, std=0.01)
        # Set all bias values of the projection layer to 0 initially
        # else bias will dominate early on and almost all gates become stuck near 0/1
        nn.init.zeros_(self.proj.bias)

    @staticmethod
    # normal min() is not differentiable so we replace with soft minimun
    def _soft_min3(a, b, c, gamma):
        x = torch.stack([-a, -b, -c], dim=-1) / gamma
        return -gamma * torch.logsumexp(x, dim=-1)

    def _soft_dtw(self, seq_a, seq_b):
        N, T = seq_a.shape
        K    = seq_b.shape[0]
        # create cost tables
        R    = torch.full((N, K, T+1, T+1), 1e9, device=seq_a.device, dtype=seq_a.dtype)
        R[:, :, 0, 0] = 0.0
        for k in range(2 * T - 1):
            i_lo = max(1, k + 2 - T)
            i_hi = min(T, k + 1)
            if i_lo > i_hi:
                continue
            i_v = torch.arange(i_lo, i_hi + 1, device=seq_a.device)
            j_v = k + 2 - i_v
            mask = (i_v - j_v).abs() <= self.bandwidth
            i_v, j_v = i_v[mask], j_v[mask]
            if len(i_v) == 0:
                continue
            d = (seq_a[:, i_v-1].unsqueeze(1) - seq_b[:, j_v-1].unsqueeze(0)) ** 2
            R[:, :, i_v, j_v] = d + self._soft_min3(
                R[:, :, i_v-1, j_v], R[:, :, i_v, j_v-1],
                R[:, :, i_v-1, j_v-1], self.gamma)
        return R[:, :, T, T]

    def forward(self, x):
        B, C, D, H, W = x.shape
        # take average of each 7x7 block - now each channel has one spectral signature
        spec = x.mean(dim=(-2, -1))
        # batch and channels - one dimension (2048 spectra; each length 188)
        spec_flat = spec.reshape(B * C, D)
        # AdaptiveAvgPool1d needs (batch, channels, length) (188 to 24)
        spec_comp = self.spec_compress(spec_flat.unsqueeze(1)).squeeze(1)
        # Subtract the average so DTW compares curve shape rather than intensity level.
        spec_n    = spec_comp  - spec_comp.mean(dim=-1, keepdim=True)
        proto_n   = self.prototypes - self.prototypes.mean(dim=-1, keepdim=True)

        cost      = self._soft_dtw(spec_n, proto_n)
        scale     = self.log_scale.exp().clamp(min=0.1)
        # convert distance to similarity
        # reshape back into (B,C,K) and take average
        # Prototypex score = average similarity over all channels
        sim       = torch.exp(-cost / scale).reshape(B, C, -1).mean(dim=1)
        # convert prototype similarities into channel importance
        gate      = torch.sigmoid(self.proj(sim)).view(B, C, 1, 1, 1)
        # +1 to preserve existing features while boosting useful ones
        return x * (1.0 + gate)


# GAUSSIAN INTERPOLATION

class GaussianInterpolation(nn.Module):
    def __init__(self, latent_dim, num_kernels=16):
        super().__init__()
        self.latent_dim  = latent_dim
        self.num_kernels = num_kernels
        centers = torch.linspace(0, latent_dim - 1, num_kernels)
        self.register_buffer('centers', centers)
        init_sigma = latent_dim / num_kernels
        self.log_sigma = nn.Parameter(
            torch.full((num_kernels,), float(np.log(init_sigma))))
        self.amplitude = nn.Parameter(torch.ones(num_kernels))
        self.blend     = nn.Parameter(torch.tensor(-2.0))

    def _basis_matrix(self):
        idx   = torch.arange(self.latent_dim, device=self.centers.device, dtype=torch.float32)
        diff  = idx.unsqueeze(1) - self.centers.unsqueeze(0)
        sigma = self.log_sigma.exp().unsqueeze(0) + 1e-4
        W     = torch.exp(-0.5 * (diff / sigma) ** 2)
        W     = W * self.amplitude.abs().unsqueeze(0)
        return W / (W.sum(dim=1, keepdim=True) + 1e-8)

    def forward(self, z):
        W        = self._basis_matrix()
        z_smooth = (z @ W) @ W.T
        alpha    = torch.sigmoid(self.blend)
        return alpha * z_smooth + (1.0 - alpha) * z


# ENCODER

class Conv3DBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, padding):
        super().__init__()
        self.conv = nn.Conv3d(in_channels, out_channels,
                              kernel_size=kernel_size, padding=padding, bias=False)
        self.bn = nn.BatchNorm3d(out_channels)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))


class Encoder(nn.Module):
    def __init__(self, n_bands, patch_size, latent_dim):
        super().__init__()
        # 3D Conv blocks
        self.conv_block1 = Conv3DBlock(1,  16, (7, 3, 3), (3, 1, 1))
        self.conv_block2 = Conv3DBlock(16, 32, (7, 3, 3), (3, 1, 1))

        # DTW layer
        self.dtw_layer = DTWSimilarityLayer(
            in_channels = 32,
            spectral_dim = n_bands,
            num_prototypes = CONFIG['dtw_num_prototypes'],
            proto_len = CONFIG['dtw_proto_len'],
            bandwidth = CONFIG['dtw_bandwidth'])

        self.spectral_pool = nn.AvgPool3d(kernel_size=(12, 1, 1), stride=(12, 1, 1))
        self._flat_size = self._get_flat_size(n_bands, patch_size)
        print(f"  Encoder flat size: {self._flat_size}")
        self.fc = nn.Linear(self._flat_size, 256)
        self.fc_mu = nn.Linear(256, latent_dim)
        self.fc_lvar = nn.Linear(256, latent_dim)
        nn.init.zeros_(self.fc_lvar.weight)
        nn.init.constant_(self.fc_lvar.bias, -2.0)

        # Gaussian interpolation on latent samples
        self.gauss_mu = GaussianInterpolation(latent_dim, CONFIG['gauss_num_kernels'])
        self.gauss_lvar = GaussianInterpolation(latent_dim, CONFIG['gauss_num_kernels'])

    def _get_flat_size(self, n_bands, patch_size):
        dummy = torch.zeros(1, 1, n_bands, patch_size, patch_size)
        with torch.no_grad():
            out = self.spectral_pool(self.conv_block2(self.conv_block1(dummy)))
        return int(out.numel())

    def forward(self, x):
        x = x.unsqueeze(1)
        x = self.conv_block1(x)
        x = self.conv_block2(x)
        x = self.dtw_layer(x)
        x = self.spectral_pool(x)
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc(x))
        mu      = self.fc_mu(x)
        log_var = self.fc_lvar(x).clamp(-10, 2)
        mu      = self.gauss_mu(mu)
        log_var = self.gauss_lvar(log_var)
        return mu, log_var


def reparameterize(mu, log_var):
    if not torch.is_grad_enabled():
        return mu
    return mu + torch.exp(0.5 * log_var) * torch.randn_like(log_var)


# CAPSULE NETWORK (linear routing)

def squash(tensor, dim=-1):
    sq = (tensor ** 2).sum(dim=dim, keepdim=True)
    return (sq / (1 + sq)) * tensor / (torch.sqrt(sq) + 1e-8)


class PrimaryCapsuleLayer(nn.Module):
    def __init__(self, num_capsules, in_features, out_dim):
        super().__init__()
        self.capsules = nn.ModuleList([
            nn.Linear(in_features, out_dim) for _ in range(num_capsules)
        ])

    def forward(self, z):
        outputs = torch.stack([cap(z) for cap in self.capsules], dim=1)
        return squash(outputs)


class LinearCapsuleLayer(nn.Module):
    # Input: 16 capsules × 8 dimensions
    # Output: 12 mineral capsules × 16 dimensions
    def __init__(self, num_classes, num_primary, primary_dim, class_dim):
        super().__init__()
        self.W = nn.Linear(num_primary * primary_dim,
                           num_classes * class_dim, bias=True)
        self.num_classes = num_classes
        self.class_dim   = class_dim
        nn.init.normal_(self.W.weight, std=0.01)

    def forward(self, x):
        B      = x.size(0)
        # flatten capsules
        x_flat = x.reshape(B, -1)
        out    = self.W(x_flat).view(B, self.num_classes, self.class_dim)
        return squash(out)


class DUENetCapsule(nn.Module):
    def __init__(self):
        super().__init__()
        self.primary_capsules = PrimaryCapsuleLayer(
            num_capsules=NUM_PRIMARY_CAPS,
            in_features=LATENT_DIM,
            out_dim=PRIMARY_CAP_DIM)
        self.mineral_capsules = LinearCapsuleLayer(
            num_classes=NUM_CLASSES,
            num_primary=NUM_PRIMARY_CAPS,
            primary_dim=PRIMARY_CAP_DIM,
            class_dim=CLASS_CAP_DIM)
        self.decoder = nn.Sequential(
            nn.Linear(CLASS_CAP_DIM * NUM_CLASSES, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Linear(256, N_BANDS),
            nn.Sigmoid())

    def forward(self, z, y=None):
        x          = self.primary_capsules(z)
        x          = self.mineral_capsules(x)
        abundances = (x ** 2).sum(dim=-1) ** 0.5
        if y is None:
            _, max_idx = abundances.max(dim=1)
            y = torch.eye(NUM_CLASSES, device=z.device).index_select(0, max_idx)
        reconstructions = self.decoder(
            (x * y[:, :, None]).reshape(x.size(0), -1))
        return abundances, reconstructions


# LOSS FUNCTIONS

# latent space should resemble standard Gaussian.
def loss_variational(mu, log_var, beta):
    kl = -0.5 * torch.mean(1 + log_var - mu.pow(2) - log_var.exp())
    # controls influence else kl dominates in the beginning
    return beta * kl

# compare shapes
def loss_spectral_dissimilarity(x_input, x_recon):
    # normalise vectors
    x_norm  = F.normalize(x_input, dim=1)
    r_norm  = F.normalize(x_recon,  dim=1)
    # dot pdt
    cos_sim = (x_norm * r_norm).sum(dim=1).clamp(-1 + 1e-6, 1 - 1e-6)
    # calculate angle and return single scalar
    return torch.mean(torch.acos(cos_sim))

# compare local structure
def loss_structural_dissimilarity(x_input, x_recon):
    C1, C2 = 0.9, 1.5
    xi = x_input.unsqueeze(1)
    xr = x_recon.unsqueeze(1)
    mu_x     = F.avg_pool1d(xi,     kernel_size=11, stride=1, padding=5)
    mu_r     = F.avg_pool1d(xr,     kernel_size=11, stride=1, padding=5)
    sigma_x  = F.avg_pool1d(xi**2,  kernel_size=11, stride=1, padding=5) - mu_x**2
    sigma_r  = F.avg_pool1d(xr**2,  kernel_size=11, stride=1, padding=5) - mu_r**2
    sigma_xr = F.avg_pool1d(xi*xr,  kernel_size=11, stride=1, padding=5) - mu_x*mu_r
    ssim     = ((2*mu_x*mu_r + C1)*(2*sigma_xr + C2)) / \
               ((mu_x**2 + mu_r**2 + C1)*(sigma_x + sigma_r + C2))
    return torch.mean(1 - ssim)

# Force correct mineral abundance high and incorrect ones low.
def loss_capsule_margin(abundances, labels_onehot):
    left  = F.relu(0.9 - abundances) ** 2
    right = F.relu(abundances - 0.1) ** 2
    # applies left loss only to correct class and applies right loss to wrong classes
    return (labels_onehot * left + 0.5 * (1 - labels_onehot) * right).mean()

def total_loss(mu, log_var, x_center, x_recon, abundances, labels_onehot, beta):
    L_G  = loss_variational(mu, log_var, beta)
    L_S  = loss_spectral_dissimilarity(x_center, x_recon)
    L_SD = loss_structural_dissimilarity(x_center, x_recon)
    L_C  = loss_capsule_margin(abundances, labels_onehot)
    L    = CONFIG['gamma1'] * (L_G + L_S + L_SD) + CONFIG['gamma2'] * L_C
    return L, {'L_G': L_G.item(), 'L_S': L_S.item(),
                'L_SD': L_SD.item(), 'L_C': L_C.item()}

# increase beta gradually
def get_beta(epoch, warmup, max_beta):
    return max_beta * min(1.0, epoch / warmup)

# reconstruction done for center pixel only
def get_center_spectrum(patches):
    center = CONFIG['patch_size'] // 2
    return patches[:, :, center, center]


# BUILD MODEL

encoder = Encoder(CONFIG['n_bands'], CONFIG['patch_size'],
                  CONFIG['latent_dim']).to(DEVICE)
capsnet = DUENetCapsule().to(DEVICE)

# count paramters
enc_params  = sum(p.numel() for p in encoder.parameters() if p.requires_grad)
caps_params = sum(p.numel() for p in capsnet.parameters() if p.requires_grad)
print(f"\nEncoder parameters:  {enc_params:,}")
print(f"CapsNet parameters:  {caps_params:,}")
print(f"Total parameters:    {enc_params + caps_params:,}")

# combine parameters
all_params = list(encoder.parameters()) + list(capsnet.parameters())

optimizer  = Adam(all_params, lr=CONFIG['lr'])

# learning rate scheduler
# The model should learn aggressively at the beginning, and make smaller adjustments later.
scheduler  = CosineAnnealingLR(
    optimizer,
    T_max=CONFIG['epochs'],
    eta_min=CONFIG['lr'] * 0.05)   # decays to 5% of peak LR


# TRAINING LOOP

def train_one_epoch(encoder, capsnet, loader, optimizer, beta):
    encoder.train()
    capsnet.train()
    total    = 0.0
    comp_sum = {'L_G': 0, 'L_S': 0, 'L_SD': 0, 'L_C': 0}

    for patches, abuns_gt, labels in loader:
        patches       = patches.to(DEVICE, non_blocking=True)
        labels        = labels.to(DEVICE,  non_blocking=True)
        labels_onehot = torch.eye(NUM_CLASSES, device=DEVICE)[labels]
        x_center      = get_center_spectrum(patches)

        mu, log_var         = encoder(patches)
        z                   = reparameterize(mu, log_var)
        abundances, x_recon = capsnet(z, labels_onehot)

        loss, comps = total_loss(
            mu, log_var, x_center, x_recon, abundances, labels_onehot, beta)

        optimizer.zero_grad()
        loss.backward()
        torch.nn.utils.clip_grad_norm_(all_params, max_norm=1.0)
        optimizer.step()

        total += loss.item()
        for k in comp_sum:
            comp_sum[k] += comps[k]

    n = len(loader)
    return total / n, {k: v / n for k, v in comp_sum.items()}


@torch.no_grad()
def evaluate(encoder, capsnet, loader, per_class=False):
    encoder.eval()
    capsnet.eval()
    correct   = 0
    total     = 0
    nrmse_sum = 0.0
    class_correct = np.zeros(NUM_CLASSES)
    class_total   = np.zeros(NUM_CLASSES)

    confusion = np.zeros((NUM_CLASSES, NUM_CLASSES), dtype=np.int64)

    for patches, abuns_gt, labels in loader:
        patches  = patches.to(DEVICE,  non_blocking=True)
        abuns_gt = abuns_gt.to(DEVICE, non_blocking=True)
        labels   = labels.to(DEVICE,   non_blocking=True)

        mu, log_var   = encoder(patches)
        z             = reparameterize(mu, log_var)
        abundances, _ = capsnet(z)

        preds = abundances.argmax(dim=1)
        correct   += (preds == labels).sum().item()
        total     += labels.size(0)
        nrmse_sum += torch.sqrt(
            ((abundances - abuns_gt)**2).mean(dim=1)).sum().item()

        # Fill confusion matrix
        preds_np  = preds.cpu().numpy()
        labels_np = labels.cpu().numpy()
        for p, t in zip(preds_np, labels_np):
            confusion[t, p] += 1

        if per_class:
            for cls in range(NUM_CLASSES):
                mask = (labels == cls)
                class_total[cls]   += mask.sum().item()
                class_correct[cls] += (preds[mask] == cls).sum().item()

    acc  = 100 * correct / total
    nrmse = nrmse_sum / total

    # Kappa calculation
    n     = confusion.sum()
    # observed agreement
    po    = np.diag(confusion).sum() / n
    pe    = (confusion.sum(axis=1) * confusion.sum(axis=0)).sum() / (n ** 2)
    kappa = (po - pe) / (1 - pe + 1e-10)


    if per_class:
        return acc, nrmse, kappa, class_correct, class_total
    return acc, nrmse, kappa


# RUN

print(f"\n{'='*65}")
print(f"DUENet FULL SCALE — {CONFIG['epochs']} epochs on {DEVICE}")
print(f"Latent: {LATENT_DIM} | Primary caps: {NUM_PRIMARY_CAPS}×{PRIMARY_CAP_DIM} | "
      f"Class caps: {NUM_CLASSES}×{CLASS_CAP_DIM}")
print(f"DTW: {CONFIG['dtw_num_prototypes']} prototypes × {CONFIG['dtw_proto_len']} len | "
      f"Gauss: {CONFIG['gauss_num_kernels']} kernels")
print(f"KL warmup: {CONFIG['kl_warmup_epochs']} epochs → β={CONFIG['beta_kl']}")
print(f"{'='*65}")

best_acc    = 0.0
epoch_times = []
history     = []

for epoch in range(1, CONFIG['epochs'] + 1):
    t0   = time.time()
    beta = get_beta(epoch, CONFIG['kl_warmup_epochs'], CONFIG['beta_kl'])

    train_loss, comps = train_one_epoch(
        encoder, capsnet, train_loader, optimizer, beta)

    do_per_class = (epoch % CONFIG['save_every'] == 0 or epoch == CONFIG['epochs'])

    if do_per_class:
        train_acc, train_nrmse, train_kappa = evaluate(encoder, capsnet, train_loader)
        test_acc, test_nrmse, test_kappa, cls_correct, cls_total = evaluate(
            encoder, capsnet, test_loader, per_class=True)
    else:
        train_acc, train_nrmse, train_kappa = evaluate(encoder, capsnet, train_loader)
        test_acc,  test_nrmse, test_kappa  = evaluate(encoder, capsnet, test_loader)

    scheduler.step()
    elapsed = time.time() - t0
    epoch_times.append(elapsed)
    eta = np.mean(epoch_times) * (CONFIG['epochs'] - epoch)

    lr_now = optimizer.param_groups[0]['lr']
    print(f"Ep {epoch:3d}/{CONFIG['epochs']} | β={beta:.3f} | lr={lr_now:.2e} | "
          f"Loss:{train_loss:.4f} | "
          f"Train:{train_acc:.1f}% | Test:{test_acc:.1f}% | "
          f"Kappa:{test_kappa:.4f} | NRMSE:{test_nrmse:.4f} | "
          f"{elapsed:.1f}s | ETA:{eta/60:.1f}min")
    print(f"  L_G:{comps['L_G']:.4f} "
          f"L_S:{comps['L_S']:.4f} "
          f"L_SD:{comps['L_SD']:.4f} "
          f"L_C:{comps['L_C']:.4f}")

    history.append({
        'epoch': epoch, 'loss': train_loss,
        'train_acc': train_acc, 'test_acc': test_acc,
        'test_nrmse': test_nrmse, **comps
    })


    # Per-class breakdown
    if do_per_class:
        print(f"\n  Per-class accuracy (test):")
        for i, name in enumerate(MINERAL_NAMES):
            if cls_total[i] > 0:
                cls_acc = 100 * cls_correct[i] / cls_total[i]
                bar     = '█' * int(cls_acc / 5)
                print(f"    {i:2d} {name:<20s}: {cls_acc:5.1f}% {bar}")

    # Save best
    if test_acc > best_acc:
        best_acc = test_acc
        torch.save({
            'encoder':     encoder.state_dict(),
            'capsnet':     capsnet.state_dict(),
            'config':      CONFIG,
            'epoch':       epoch,
            'test_acc':    test_acc,
            'test_kappa':  test_kappa,
            'test_nrmse':  test_nrmse,
            'history':     history,
        }, os.path.join(CONFIG['save_dir'], 'duenet_best.pth'))
        print(f"Best saved ({test_acc:.2f}%)")

    # Periodic checkpoint
    if epoch % CONFIG['save_every'] == 0:
        torch.save({
            'encoder':    encoder.state_dict(),
            'capsnet':    capsnet.state_dict(),
            'optimizer':  optimizer.state_dict(),
            'scheduler':  scheduler.state_dict(),
            'config':     CONFIG,
            'epoch':      epoch,
            'test_acc':   test_acc,
            'history':    history,
        }, os.path.join(CONFIG['save_dir'], f'duenet_epoch{epoch:03d}.pth'))
        print(f"Checkpoint saved (epoch {epoch})")


# FINAL REPORT

total_time = sum(epoch_times)
print(f"\n{'='*65}")
print(f"Training complete")
print(f"Total time:     {total_time/60:.1f} min ({total_time/3600:.2f} hr)")
print(f"Best test acc:  {best_acc:.2f}%")
print(f"Avg epoch time: {np.mean(epoch_times):.1f}s")

# Final per-class evaluation on best model
print(f"\nLoading best model for final evaluation...")
ckpt = torch.load(os.path.join(CONFIG['save_dir'], 'duenet_best.pth'), map_location=DEVICE)
encoder.load_state_dict(ckpt['encoder'])
capsnet.load_state_dict(ckpt['capsnet'])

final_train_acc, final_train_nrmse, final_train_kappa = evaluate(encoder, capsnet, train_loader)
final_test_acc, final_test_nrmse, final_test_kappa, cls_correct, cls_total = evaluate(
    encoder, capsnet, test_loader, per_class=True)

print(f"\nFinal results (best model from epoch {ckpt['epoch']}):")
print(f"  Train accuracy: {final_train_acc:.2f}%")
print(f"  Test  accuracy: {final_test_acc:.2f}%")
print(f"  Test  NRMSE:    {final_test_nrmse:.4f}")
print(f"\n  Per-class test accuracy:")
for i, name in enumerate(MINERAL_NAMES):
    if cls_total[i] > 0:
        cls_acc = 100 * cls_correct[i] / cls_total[i]
        bar     = '█' * int(cls_acc / 5)
        print(f"    {i:2d} {name:<20s}: {cls_acc:5.1f}%  n={int(cls_total[i]):5,d}  {bar}")

print(f"\nSaved files:")
print(f"  Best model:  {CONFIG['save_dir']}duenet_best.pth")
print(f"  Checkpoints: {CONFIG['save_dir']}duenet_epoch***.pth")