# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1125hUIH2kUwTfynnv1yVjvf_8f0M_y6l
"""

# DUENet — Evaluate Synthetic-Trained Model on Real Cuprite AVIRIS Data

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
import time
import os

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Device: {DEVICE}")

SYNTHETIC_MODEL_PATH = '/content/duenet_best.pth'
REAL_HSI_PATH        = '/content/hsi_real.npy'
REAL_ABUN_PATH       = '/content/abundances_real.npy'

MINERAL_NAMES = [
    'Alunite', 'Andradite', 'Buddingtonite', 'Dumortierite',
    'Kaolinite_1', 'Kaolinite_2', 'Muscovite', 'Montmorillonite',
    'Nontronite', 'Pyrope', 'Sphene', 'Chalcedony'
]

# LOAD CHECKPOINT — config from saved model

print(f"\nLoading checkpoint: {SYNTHETIC_MODEL_PATH}")
ckpt = torch.load(SYNTHETIC_MODEL_PATH, map_location=DEVICE, weights_only=False)

CONFIG = ckpt['config']
print(f"Model trained with config:")
print(f"  n_bands:         {CONFIG['n_bands']}")
print(f"  n_classes:       {CONFIG['n_classes']}")
print(f"  patch_size:      {CONFIG['patch_size']}")
print(f"  latent_dim:      {CONFIG['latent_dim']}")
print(f"  Trained OA:      {ckpt.get('test_acc', 'N/A'):.2f}%")
print(f"  Trained NRMSE:   {ckpt.get('test_nrmse', 'N/A'):.4f}")

NUM_CLASSES      = CONFIG['n_classes']
LATENT_DIM       = CONFIG['latent_dim']
NUM_PRIMARY_CAPS = CONFIG['num_primary_caps']
PRIMARY_CAP_DIM  = CONFIG['primary_cap_dim']
CLASS_CAP_DIM    = CONFIG['class_cap_dim']
N_BANDS          = CONFIG['n_bands']
PATCH_SIZE       = CONFIG['patch_size']

# LOAD REAL DATA

print(f"\nLoading real AVIRIS Cuprite data...")
hsi        = np.load(REAL_HSI_PATH).astype(np.float32)
abundances = np.load(REAL_ABUN_PATH).astype(np.float32)

# Fix shape - (rows, cols, bands)
if hsi.shape[1] == N_BANDS:
    hsi = hsi.transpose(2, 0, 1)
    print(f"Fixed HSI shape: {hsi.shape}")
if hsi.shape[2] != N_BANDS:
    raise ValueError(f"HSI has {hsi.shape[2]} bands but model expects {N_BANDS}")

# Fix abundance shape if needed
if abundances.shape[2] != NUM_CLASSES:
    if abundances.shape[0] == NUM_CLASSES:
        abundances = abundances.transpose(1, 2, 0)
    elif abundances.shape[1] == NUM_CLASSES:
        abundances = abundances.transpose(0, 2, 1)

rows, cols, _ = hsi.shape
label_map     = np.argmax(abundances, axis=2)

print(f"HSI shape:        {hsi.shape}")
print(f"Abundances shape: {abundances.shape}")
print(f"Label map shape:  {label_map.shape}")
print(f"Label map range:  0 to {label_map.max()}")

# Verify dimensions match
assert hsi.shape[0] == abundances.shape[0], "Row mismatch between HSI and abundances"
assert hsi.shape[1] == abundances.shape[1], "Col mismatch between HSI and abundances"

# Class distribution
print(f"\nClass distribution in real data:")
for i, name in enumerate(MINERAL_NAMES):
    count = (label_map == i).sum()
    pct   = 100 * count / label_map.size
    print(f"  {i:2d} {name:<20s}: {count:8,d} ({pct:5.1f}%)")

HALF       = PATCH_SIZE // 2
hsi_padded = np.pad(hsi,
    pad_width=((HALF, HALF), (HALF, HALF), (0, 0)), mode='reflect')

all_coords = np.array([(r, c) for r in range(rows) for c in range(cols)])
print(f"\nTotal pixels for evaluation: {len(all_coords):,}")


class CupriteDataset(Dataset):
    def __init__(self, coords, hsi_padded, abundances, label_map, patch_size):
        self.coords     = coords
        self.hsi_padded = hsi_padded
        self.abundances = abundances
        self.label_map  = label_map
        self.half       = patch_size // 2

    def __len__(self):
        return len(self.coords)

    def __getitem__(self, idx):
        r, c   = self.coords[idx]
        rp, cp = r + self.half, c + self.half
        patch  = self.hsi_padded[rp-self.half:rp+self.half+1,
                                  cp-self.half:cp+self.half+1, :]
        patch  = patch.transpose(2, 0, 1)
        return (torch.tensor(patch,              dtype=torch.float32),
                torch.tensor(abundances[r, c],   dtype=torch.float32),
                torch.tensor(label_map[r, c],    dtype=torch.long))


eval_loader = DataLoader(
    CupriteDataset(all_coords, hsi_padded, abundances,
                   label_map, PATCH_SIZE),
    batch_size=256, shuffle=False, num_workers=2, pin_memory=True)

print(f"Eval batches: {len(eval_loader)}")


class DTWSimilarityLayer(nn.Module):
    def __init__(self, in_channels, spectral_dim,
                 num_prototypes, proto_len, bandwidth, gamma=1.0):
        super().__init__()
        self.proto_len  = proto_len
        self.bandwidth  = bandwidth
        self.gamma      = gamma
        self.prototypes    = nn.Parameter(torch.randn(num_prototypes, proto_len) * 0.1)
        self.spec_compress = nn.AdaptiveAvgPool1d(proto_len)
        self.log_scale     = nn.Parameter(torch.tensor(0.0))
        self.proj          = nn.Linear(num_prototypes, in_channels, bias=True)
        nn.init.normal_(self.proj.weight, std=0.01)
        nn.init.zeros_(self.proj.bias)

    @staticmethod
    def _soft_min3(a, b, c, gamma):
        x = torch.stack([-a, -b, -c], dim=-1) / gamma
        return -gamma * torch.logsumexp(x, dim=-1)

    def _soft_dtw(self, seq_a, seq_b):
        N, T = seq_a.shape
        K    = seq_b.shape[0]
        R    = torch.full((N, K, T+1, T+1), 1e9, device=seq_a.device, dtype=seq_a.dtype)
        R[:, :, 0, 0] = 0.0
        for k in range(2 * T - 1):
            i_lo = max(1, k + 2 - T)
            i_hi = min(T, k + 1)
            if i_lo > i_hi:
                continue
            i_v = torch.arange(i_lo, i_hi + 1, device=seq_a.device)
            j_v = k + 2 - i_v
            mask = (i_v - j_v).abs() <= self.bandwidth
            i_v, j_v = i_v[mask], j_v[mask]
            if len(i_v) == 0:
                continue
            d = (seq_a[:, i_v-1].unsqueeze(1) - seq_b[:, j_v-1].unsqueeze(0)) ** 2
            R[:, :, i_v, j_v] = d + self._soft_min3(
                R[:, :, i_v-1, j_v], R[:, :, i_v, j_v-1],
                R[:, :, i_v-1, j_v-1], self.gamma)
        return R[:, :, T, T]

    def forward(self, x):
        B, C, D, H, W = x.shape
        spec      = x.mean(dim=(-2, -1))
        spec_flat = spec.reshape(B * C, D)
        spec_comp = self.spec_compress(spec_flat.unsqueeze(1)).squeeze(1)
        spec_n    = spec_comp  - spec_comp.mean(dim=-1, keepdim=True)
        proto_n   = self.prototypes - self.prototypes.mean(dim=-1, keepdim=True)
        cost      = self._soft_dtw(spec_n, proto_n)
        scale     = self.log_scale.exp().clamp(min=0.1)
        sim       = torch.exp(-cost / scale).reshape(B, C, -1).mean(dim=1)
        gate      = torch.sigmoid(self.proj(sim)).view(B, C, 1, 1, 1)
        return x * (1.0 + gate)


class GaussianInterpolation(nn.Module):
    def __init__(self, latent_dim, num_kernels=16):
        super().__init__()
        self.latent_dim  = latent_dim
        self.num_kernels = num_kernels
        centers = torch.linspace(0, latent_dim - 1, num_kernels)
        self.register_buffer('centers', centers)
        init_sigma = latent_dim / num_kernels
        self.log_sigma = nn.Parameter(
            torch.full((num_kernels,), float(np.log(init_sigma))))
        self.amplitude = nn.Parameter(torch.ones(num_kernels))
        self.blend     = nn.Parameter(torch.tensor(-2.0))

    def _basis_matrix(self):
        idx   = torch.arange(self.latent_dim, device=self.centers.device, dtype=torch.float32)
        diff  = idx.unsqueeze(1) - self.centers.unsqueeze(0)
        sigma = self.log_sigma.exp().unsqueeze(0) + 1e-4
        W     = torch.exp(-0.5 * (diff / sigma) ** 2)
        W     = W * self.amplitude.abs().unsqueeze(0)
        return W / (W.sum(dim=1, keepdim=True) + 1e-8)

    def forward(self, z):
        W        = self._basis_matrix()
        z_smooth = (z @ W) @ W.T
        alpha    = torch.sigmoid(self.blend)
        return alpha * z_smooth + (1.0 - alpha) * z


class Conv3DBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, padding):
        super().__init__()
        self.conv = nn.Conv3d(in_channels, out_channels,
                              kernel_size=kernel_size, padding=padding, bias=False)
        self.bn   = nn.BatchNorm3d(out_channels)
        self.relu = nn.ReLU(inplace=True)

    def forward(self, x):
        return self.relu(self.bn(self.conv(x)))


class Encoder(nn.Module):
    def __init__(self, n_bands, patch_size, latent_dim):
        super().__init__()
        self.conv_block1 = Conv3DBlock(1,  16, (7, 3, 3), (3, 1, 1))
        self.conv_block2 = Conv3DBlock(16, 32, (7, 3, 3), (3, 1, 1))
        self.dtw_layer   = DTWSimilarityLayer(
            in_channels=32, spectral_dim=n_bands,
            num_prototypes=CONFIG['dtw_num_prototypes'],
            proto_len=CONFIG['dtw_proto_len'],
            bandwidth=CONFIG['dtw_bandwidth'])
        self.spectral_pool = nn.AvgPool3d(kernel_size=(12, 1, 1), stride=(12, 1, 1))
        self._flat_size    = self._get_flat_size(n_bands, patch_size)
        self.fc      = nn.Linear(self._flat_size, 256)
        self.fc_mu   = nn.Linear(256, latent_dim)
        self.fc_lvar = nn.Linear(256, latent_dim)
        nn.init.zeros_(self.fc_lvar.weight)
        nn.init.constant_(self.fc_lvar.bias, -2.0)
        self.gauss_mu   = GaussianInterpolation(latent_dim, CONFIG['gauss_num_kernels'])
        self.gauss_lvar = GaussianInterpolation(latent_dim, CONFIG['gauss_num_kernels'])

    def _get_flat_size(self, n_bands, patch_size):
        dummy = torch.zeros(1, 1, n_bands, patch_size, patch_size)
        with torch.no_grad():
            out = self.spectral_pool(self.conv_block2(self.conv_block1(dummy)))
        return int(out.numel())

    def forward(self, x):
        x = x.unsqueeze(1)
        x = self.conv_block1(x)
        x = self.conv_block2(x)
        x = self.dtw_layer(x)
        x = self.spectral_pool(x)
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc(x))
        mu      = self.fc_mu(x)
        log_var = self.fc_lvar(x).clamp(-10, 2)
        mu      = self.gauss_mu(mu)
        log_var = self.gauss_lvar(log_var)
        return mu, log_var


def reparameterize(mu, log_var):
    if not torch.is_grad_enabled():
        return mu
    return mu + torch.exp(0.5 * log_var) * torch.randn_like(log_var)


def squash(tensor, dim=-1):
    sq = (tensor ** 2).sum(dim=dim, keepdim=True)
    return (sq / (1 + sq)) * tensor / (torch.sqrt(sq) + 1e-8)


class PrimaryCapsuleLayer(nn.Module):
    def __init__(self, num_capsules, in_features, out_dim):
        super().__init__()
        self.capsules = nn.ModuleList([
            nn.Linear(in_features, out_dim) for _ in range(num_capsules)
        ])

    def forward(self, z):
        outputs = torch.stack([cap(z) for cap in self.capsules], dim=1)
        return squash(outputs)


class LinearCapsuleLayer(nn.Module):
    def __init__(self, num_classes, num_primary, primary_dim, class_dim):
        super().__init__()
        self.W = nn.Linear(num_primary * primary_dim,
                           num_classes * class_dim, bias=True)
        self.num_classes = num_classes
        self.class_dim   = class_dim
        nn.init.normal_(self.W.weight, std=0.01)

    def forward(self, x):
        B      = x.size(0)
        x_flat = x.reshape(B, -1)
        out    = self.W(x_flat).view(B, self.num_classes, self.class_dim)
        return squash(out)


class DUENetCapsule(nn.Module):
    def __init__(self):
        super().__init__()
        self.primary_capsules = PrimaryCapsuleLayer(
            num_capsules=NUM_PRIMARY_CAPS,
            in_features=LATENT_DIM,
            out_dim=PRIMARY_CAP_DIM)
        self.mineral_capsules = LinearCapsuleLayer(
            num_classes=NUM_CLASSES,
            num_primary=NUM_PRIMARY_CAPS,
            primary_dim=PRIMARY_CAP_DIM,
            class_dim=CLASS_CAP_DIM)
        self.decoder = nn.Sequential(
            nn.Linear(CLASS_CAP_DIM * NUM_CLASSES, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Linear(256, N_BANDS),
            nn.Sigmoid())

    def forward(self, z, y=None):
        x          = self.primary_capsules(z)
        x          = self.mineral_capsules(x)
        abundances = (x ** 2).sum(dim=-1) ** 0.5
        if y is None:
            _, max_idx = abundances.max(dim=1)
            y = torch.eye(NUM_CLASSES, device=z.device).index_select(0, max_idx)
        reconstructions = self.decoder(
            (x * y[:, :, None]).reshape(x.size(0), -1))
        return abundances, reconstructions


# BUILD AND LOAD MODEL

encoder = Encoder(N_BANDS, PATCH_SIZE, LATENT_DIM).to(DEVICE)
capsnet = DUENetCapsule().to(DEVICE)

encoder.load_state_dict(ckpt['encoder'])
capsnet.load_state_dict(ckpt['capsnet'])
print(f"\nModel weights loaded successfully.")
print(f"Encoder flat size: {encoder._flat_size}")

# EVALUATION

print(f"\nRunning evaluation on real AVIRIS Cuprite...")
print(f"Total pixels: {len(all_coords):,} | Batches: {len(eval_loader)}")
print("="*60)

t_start = time.time()

correct       = 0
total         = 0
nrmse_sum     = 0.0
class_correct = np.zeros(NUM_CLASSES)
class_total   = np.zeros(NUM_CLASSES)
confusion     = np.zeros((NUM_CLASSES, NUM_CLASSES), dtype=np.int64)

encoder.eval()
capsnet.eval()
pred_abundance_list = []

with torch.no_grad():
    for batch_idx, (patches, abuns_gt, labels) in enumerate(eval_loader):
        patches  = patches.to(DEVICE,  non_blocking=True)
        abuns_gt = abuns_gt.to(DEVICE, non_blocking=True)
        labels   = labels.to(DEVICE,   non_blocking=True)

        mu, log_var   = encoder(patches)
        z             = reparameterize(mu, log_var)
        abundances, _ = capsnet(z)
        pred_abundance_list.append(abundances.cpu().numpy())

        preds     = abundances.argmax(dim=1)
        correct  += (preds == labels).sum().item()
        total    += labels.size(0)
        nrmse_sum += torch.sqrt(
            ((abundances - abuns_gt)**2).mean(dim=1)).sum().item()

        preds_np  = preds.cpu().numpy()
        labels_np = labels.cpu().numpy()
        for p, t in zip(preds_np, labels_np):
            confusion[t, p] += 1
        for cls in range(NUM_CLASSES):
            mask = (labels == cls)
            class_total[cls]   += mask.sum().item()
            class_correct[cls] += (preds[mask] == cls).sum().item()

        if (batch_idx + 1) % 100 == 0:
            print(f"  Batch {batch_idx+1}/{len(eval_loader)} | "
                  f"Running OA: {100*correct/total:.1f}%")

elapsed = time.time() - t_start

# COMPUTE FINAL METRICS

overall_acc = 100 * correct / total
mean_nrmse  = nrmse_sum / total

# Kappa coefficient
n   = confusion.sum()
po  = np.diag(confusion).sum() / n
pe  = (confusion.sum(axis=1) * confusion.sum(axis=0)).sum() / (n ** 2)
kappa = (po - pe) / (1 - pe + 1e-10)

# Mean class accuracy (average per-class accuracy, not overall)
per_class_acc = []
for cls in range(NUM_CLASSES):
    if class_total[cls] > 0:
        per_class_acc.append(100 * class_correct[cls] / class_total[cls])
mean_class_acc = np.mean(per_class_acc)

# PRINT RESULTS

print(f"\n{'='*60}")
print(f"RESULTS — Synthetic-trained model on Real AVIRIS Cuprite")
print(f"{'='*60}")
print(f"Overall Accuracy (OA):    {overall_acc:.2f}%")
print(f"Kappa coefficient:        {kappa:.4f}")
print(f"Mean Class Accuracy:      {mean_class_acc:.2f}%")
print(f"Mean NRMSE:               {mean_nrmse:.4f}")
print(f"Eval time:                {elapsed:.1f}s")

print(f"\nPer-class accuracy:")
for cls in range(NUM_CLASSES):
    name = MINERAL_NAMES[cls] if cls < len(MINERAL_NAMES) else f'Class {cls}'
    if class_total[cls] > 0:
        ca  = 100 * class_correct[cls] / class_total[cls]
        bar = '█' * int(ca / 5)
        print(f"  {cls:2d} {name:<20s}: {ca:5.1f}%  n={int(class_total[cls]):7,d}  {bar}")


print(f"{'='*60}")
print(f"{'Dataset':<25} {'Type':<12} {'OA':>8} {'Kappa':>8} {'NRMSE':>8}")
print(f"{'-'*61}")
print(f"{'Synthetic Cuprite':<25} {'Synthetic':<12} {'~94%':>8} {'~0.93':>8} {'~0.10':>8}")
print(f"{'Real AVIRIS Cuprite':<25} {'Real':<12} {overall_acc:>7.2f}% {kappa:>8.4f} {mean_nrmse:>8.4f}")
print(f"{'Real Cuprite':<25} {'Real':<12} {'~57%':>8} {'~0.51':>8} {'N/A':>8}")
print(f"{'DUENet (paper)':<25} {'Synthetic':<12} {'97.56%':>8} {'0.95':>8} {'0.12':>8}")